variables:
  system.debug: false
  major: 11 # Align with Cms/Commerce version
  minor: 8 # Up when breaking changes

name: $(major).$(minor).$(rev:r) #Build.BuildNumber

trigger:
  batch: true
  branches:
      include:
      - main
      - master
      - release/*

pool:
  vmImage: windows-2019

steps:
- template: .azuredevops/epinova-nuget-steps.yml
  parameters:
    dotnetVersions: []
    dotnetTestFilter: FullyQualifiedName!~IntegrationTests
    nugetPushServiceConnection: Nuget.org push

- task: GithubRelease@1 
  displayName: 'Create GitHub Release'      
  inputs:
    gitHubConnection: github.com_otanum
    repositoryName: Epinova/Epinova.Elasticsearch           
    assets: $(Build.ArtifactStagingDirectory)/*.nupkg