#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Epinova.ElasticSearch.Core.EPiServer.Extensions;
    using Epinova.ElasticSearch.Core.Utilities;
    using EPiServer;
    using EPiServer.Core;
    using EPiServer.Editor;
    using EPiServer.Framework.Localization;
    using EPiServer.Security;
    using EPiServer.SpecializedProperties;
    using EPiServer.Web;
    using EPiServer.Web.Mvc.Html;
    using EPiServer.Web.Routing;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ElasticSearchAdmin/Boosting/Index.cshtml")]
    public partial class _Views_ElasticSearchAdmin_Boosting_Index_cshtml : System.Web.Mvc.WebViewPage<Epinova.ElasticSearch.Core.EPiServer.Models.BoostingViewModel>
    {

#line default
#line hidden
public System.Web.WebPages.HelperResult PageName(string typeKey)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
    string key = typeKey.Split('_').Last();
    
WriteTo(__razor_helper_writer, LocalizationService.Current.GetString("/contenttypes/" + key + "/name"));

                                                                            

});

#line default
#line hidden
}
#line default
#line hidden

#line default
#line hidden
public System.Web.WebPages.HelperResult TabName(string key)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {
 
    
WriteTo(__razor_helper_writer, LocalizationService.Current.GetString("/groups/" + key));

                                                            

});

#line default
#line hidden
}
#line default
#line hidden

        public _Views_ElasticSearchAdmin_Boosting_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

  
    Layout = "~/Views/ElasticSearchAdmin/_ElasticSearch.cshtml";

WriteLiteral("\r\n\r\n");

 if (Model == null)
{
    return;
}

WriteLiteral("\r\n");

  
    string localizationPath = "/epinovaelasticsearch/boosting/";

WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"epi-parentContainer\"");

WriteLiteral(">\r\n\r\n    <h1");

WriteLiteral(" class=\"EP-prefix\"");

WriteLiteral(" id=\"top\"");

WriteLiteral(">");

                              Write(Html.TranslateWithPath("heading", localizationPath));

WriteLiteral("</h1>\r\n    <p>");

  Write(Html.TranslateWithPath("description", localizationPath));

WriteLiteral("</p>\r\n\r\n    <div");

WriteLiteral(" class=\"epi-contentContainer\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

   Write(Html.TranslateWithPath("totype", localizationPath));

WriteLiteral(":\r\n        <select");

WriteLiteral(" id=\"gototype\"");

WriteLiteral(">\r\n");

            
             foreach (var type in Model.BoostingByType)
            {

WriteLiteral("                <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1181), Tuple.Create("\"", 1198)
, Tuple.Create(Tuple.Create("", 1189), Tuple.Create<System.Object, System.Int32>(type.Key
, 1189), false)
);

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1202), Tuple.Create("\"", 1219)
, Tuple.Create(Tuple.Create("", 1209), Tuple.Create("#", 1209), true)
, Tuple.Create(Tuple.Create("", 1210), Tuple.Create<System.Object, System.Int32>(type.Key
, 1210), false)
);

WriteLiteral(">");

                                                          Write(PageName(type.Key));

WriteLiteral("</a></option>\r\n");

            }

WriteLiteral("        </select>\r\n    </div>\r\n\r\n");

    
     foreach (var type in Model.BoostingByType)
    {

WriteLiteral("        <div");

WriteLiteral(" class=\"epi-contentContainer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"epi-formArea epi-marginVertical\"");

WriteLiteral(">\r\n");

                
                 using (Html.BeginForm("Save", "ElasticBoosting"))
                {
                    string group = null;


WriteLiteral("                    <div");

WriteLiteral(" class=\"epi-contentContainer\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"TypeName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1709), Tuple.Create("\"", 1726)
, Tuple.Create(Tuple.Create("", 1717), Tuple.Create<System.Object, System.Int32>(type.Key
, 1717), false)
);

WriteLiteral(" />\r\n\r\n                        <h2");

WriteAttribute("id", Tuple.Create(" id=\"", 1761), Tuple.Create("\"", 1775)
, Tuple.Create(Tuple.Create("", 1766), Tuple.Create<System.Object, System.Int32>(type.Key
, 1766), false)
);

WriteLiteral(">");

                                      Write(PageName(type.Key));

WriteLiteral("</h2>\r\n\r\n                        <table");

WriteLiteral(" class=\"epi-default\"");

WriteLiteral(">\r\n                            <thead>\r\n                                <tr>\r\n   " +
"                                 <th>");

                                   Write(Html.TranslateWithPath("property", localizationPath));

WriteLiteral("</th>\r\n                                    <th>");

                                   Write(Html.TranslateWithPath("boost", localizationPath));

WriteLiteral("</th>\r\n                                </tr>\r\n                            </thead" +
">\r\n                            <tbody>\r\n");

                                
                                 for (int i = 0; i < type.Value.Count; i++)
                                {
                                    if (type.Value[i].GroupName != group)
                                    {
                                        group = type.Value[i].GroupName;

WriteLiteral("                                        <tr>\r\n                                   " +
"         <th");

WriteLiteral(" colspan=\"2\"");

WriteLiteral("><em>");

                                                           Write(TabName(group));

WriteLiteral("</em></th>\r\n                                        </tr>\r\n");

                                    }


WriteLiteral("                                    <tr>\r\n                                       " +
" <td>\r\n                                            <input");

WriteAttribute("name", Tuple.Create(" name=\"", 2907), Tuple.Create("\"", 2930)
, Tuple.Create(Tuple.Create("", 2914), Tuple.Create("Boosting[", 2914), true)
, Tuple.Create(Tuple.Create("", 2923), Tuple.Create<System.Object, System.Int32>(i
, 2923), false)
, Tuple.Create(Tuple.Create("", 2925), Tuple.Create("].Key", 2925), true)
);

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2945), Tuple.Create("\"", 2976)
                , Tuple.Create(Tuple.Create("", 2953), Tuple.Create<System.Object, System.Int32>(type.Value[i].TypeName
, 2953), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                                            ");

                                       Write(type.Value[i].DisplayName);

WriteLiteral("\r\n                                        </td>\r\n                                " +
"        <td>\r\n                                            <select");

WriteAttribute("name", Tuple.Create(" name=\"", 3198), Tuple.Create("\"", 3223)
, Tuple.Create(Tuple.Create("", 3205), Tuple.Create("Boosting[", 3205), true)
, Tuple.Create(Tuple.Create("", 3214), Tuple.Create<System.Object, System.Int32>(i
, 3214), false)
, Tuple.Create(Tuple.Create("", 3216), Tuple.Create("].Value", 3216), true)
);

WriteLiteral(" class=\"episize240\"");

WriteLiteral(">\r\n");

                                                
                                                 foreach (int w in Enumerable.Range(1, 20))
                                                {

WriteLiteral("                                                    <option ");

                                                        Write(w == type.Value[i].Weight ? "selected" : null);

WriteLiteral(" value=\"");

                                                                                                               Write(w);

WriteLiteral("\">");

                                                                                                                   Write(w);

WriteLiteral("</option>\r\n");

                                                }

WriteLiteral("                                            </select>\r\n                          " +
"              </td>\r\n                                    </tr>\r\n");

                                }

WriteLiteral("                            </tbody>\r\n                        </table>\r\n         " +
"           </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"epi-buttonContainer\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"epi-cmsButton\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" class=\"epi-cmsButton-text epi-cmsButton-tools epi-cmsButton-Save\"");

WriteLiteral(" type=\"submit\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4077), Tuple.Create("\"", 4134)
                                          , Tuple.Create(Tuple.Create("", 4085), Tuple.Create<System.Object, System.Int32>(Html.TranslateWithPath("save", localizationPath)
, 4085), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 4135), Tuple.Create("\"", 4192)
                                                                                                    , Tuple.Create(Tuple.Create("", 4143), Tuple.Create<System.Object, System.Int32>(Html.TranslateWithPath("save", localizationPath)
, 4143), false)
);

WriteLiteral(" />\r\n                        </span>\r\n                        <span");

WriteLiteral(" class=\"epi-cmsButton\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"gototop epi-cmsButton-text epi-cmsButton-tools epi-cmsButton-ArrowLeft\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4412), Tuple.Create("\"", 4469)
                                                       , Tuple.Create(Tuple.Create("", 4420), Tuple.Create<System.Object, System.Int32>(Html.TranslateWithPath("back", localizationPath)
, 4420), false)
);

WriteLiteral(" />\r\n                        </span>\r\n                    </div>\r\n");

                }

WriteLiteral("            </div>\r\n        </div>\r\n");

    }

WriteLiteral("</div>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral(@"
    <script>
        $("".gototop"").click(function () {
            document.location.hash = '#top';
            return false;
        });

        $(""#gototype"").change(function () {
            document.location.hash = '#' + $(this).val();
            return false;
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
