using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
[assembly: ComVisible(false)]
[assembly: Guid("0818a108-083d-438b-9183-aef12733618f")]
[assembly: InternalsVisibleTo("Epinova.ElasticSearch.Core.EPiServer")]
[assembly: InternalsVisibleTo("Epinova.ElasticSearch.Core.EPiServer.Commerce")]
[assembly: InternalsVisibleTo("Core.EPiServer.Tests")]
[assembly: InternalsVisibleTo("Core.Tests")]
[assembly: InternalsVisibleTo("TestData")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]