#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Epinova.ElasticSearch.Core.EPiServer.Extensions;
    using Epinova.ElasticSearch.Core.EPiServer.Models.ViewModels;
    using EPiServer;
    using EPiServer.Core;
    using EPiServer.Editor;
    using EPiServer.Security;
    using EPiServer.SpecializedProperties;
    using EPiServer.Web;
    using EPiServer.Web.Mvc.Html;
    using EPiServer.Web.Routing;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ElasticSearchAdmin/Synonyms/Index.cshtml")]
    public partial class _Views_ElasticSearchAdmin_Synonyms_Index_cshtml : System.Web.Mvc.WebViewPage<SynonymsViewModel>
    {
        public _Views_ElasticSearchAdmin_Synonyms_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

  
    Layout = "~/Views/ElasticSearchAdmin/_ElasticSearch.cshtml";

WriteLiteral("\r\n\r\n");

 if (Model == null)
{
    return;
}

WriteLiteral("\r\n");

  
    string localizationPath = "/epinovaelasticsearch/synonyms/";

WriteLiteral("\r\n\r\n");

DefineSection("Styles", () => {

WriteLiteral(@"
    <style>
        #tabContainer .field-actions,
        #tabContainer .field-twoway {
            width: 120px;
            text-align: center;
        }

            #tabContainer .field-twoway .dijitCheckBoxDisabled {
                background-position: -15px;
            }

            #tabContainer .field-twoway .dijitCheckBoxCheckedDisabled {
                background-position: 0;
            }

            #tabContainer .field-twoway .dijitDisabled input {
                color: inherit;
            }
    </style>
");

});

WriteLiteral("\r\n<div");

WriteLiteral(" id=\"tabContainer\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" data-dojo-type=\"dijit/layout/TabContainer\"");

WriteLiteral(" doLayout=\"false\"");

WriteLiteral(">\r\n");

        
         foreach (LanguageSynonyms lang in Model.SynonymsByLanguage)
        {

WriteLiteral("            <div");

WriteLiteral(" data-dojo-type=\"dijit/layout/ContentPane\"");

WriteAttribute("title", Tuple.Create(" title=\"", 1210), Tuple.Create("\"", 1236)
, Tuple.Create(Tuple.Create("", 1218), Tuple.Create<System.Object, System.Int32>(lang.LanguageName
, 1218), false)
);

WriteLiteral(" data-dojo-props=\"");

                                                                                                   Write(lang.LanguageId == Model.CurrentLanguage ? "selected:true" : null);

WriteLiteral("\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"epi-padding-small\"");

WriteLiteral(">\r\n");

                    
                     if (ViewBag.Indices != null)
                    {
                        using (Html.BeginForm("Index", "ElasticSynonyms"))
                        {

WriteLiteral("                            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"LanguageId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1619), Tuple.Create("\"", 1643)
, Tuple.Create(Tuple.Create("", 1627), Tuple.Create<System.Object, System.Int32>(lang.LanguageId
, 1627), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                            <h2>");

                           Write(Html.TranslateWithPathRaw("index", localizationPath));

WriteLiteral("</h2>\r\n");

WriteLiteral("                            <p>\r\n                                <label>\r\n       " +
"                             <select");

WriteLiteral(" data-dojo-type=\"dijit/form/Select\"");

WriteLiteral(" name=\"index\"");

WriteLiteral(">\r\n");

                                        
                                         foreach (string index in ViewBag.Indices)
                                        {

WriteLiteral("                                            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 2087), Tuple.Create("\"", 2101)
, Tuple.Create(Tuple.Create("", 2095), Tuple.Create<System.Object, System.Int32>(index
, 2095), false)
);

WriteAttribute("selected", Tuple.Create(" selected=\"", 2102), Tuple.Create("\"", 2166)
, Tuple.Create(Tuple.Create("", 2113), Tuple.Create<System.Object, System.Int32>(ViewBag.SelectedIndex == index ? "selected" : null
, 2113), false)
);

WriteLiteral(">");

                                                                                                                               Write(index);

WriteLiteral("</option>\r\n");

                                        }

WriteLiteral("                                    </select>\r\n                                </" +
"label>\r\n                                <button");

WriteLiteral(" data-dojo-type=\"dijit/form/Button\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"epi-primary\"");

WriteLiteral(">");

                                                                                                        Write(Html.TranslateWithPathRaw("show", localizationPath));

WriteLiteral("</button>\r\n                            </p>\r\n");

                        }
                    }

WriteLiteral("\r\n");

                    
                     using (Html.BeginForm("Add", "ElasticSynonyms"))
                    {

WriteLiteral("                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"Index\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2726), Tuple.Create("\"", 2756)
, Tuple.Create(Tuple.Create("", 2734), Tuple.Create<System.Object, System.Int32>(ViewBag.SelectedIndex
, 2734), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"Analyzer\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2822), Tuple.Create("\"", 2844)
, Tuple.Create(Tuple.Create("", 2830), Tuple.Create<System.Object, System.Int32>(lang.Analyzer
, 2830), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"LanguageId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2912), Tuple.Create("\"", 2936)
, Tuple.Create(Tuple.Create("", 2920), Tuple.Create<System.Object, System.Int32>(lang.LanguageId
, 2920), false)
);

WriteLiteral(" />\r\n");



WriteLiteral("                        <h2>");

                       Write(Html.TranslateWithPath("newsynonym", localizationPath));

WriteLiteral("</h2>\r\n");

WriteLiteral("                        <p>\r\n                            <input");

WriteLiteral(" data-dojo-type=\"dijit/form/ValidationTextBox\"");

WriteLiteral(" name=\"from\"");

WriteLiteral(" data-dojo-props=\"placeholder:\'");

                                                                                                                      Write(Html.TranslateWithPathRaw("from", localizationPath));

WriteLiteral("\',required:true\"");

WriteLiteral(" />\r\n                            <input");

WriteLiteral(" data-dojo-type=\"dijit/form/ValidationTextBox\"");

WriteLiteral(" name=\"to\"");

WriteLiteral(" data-dojo-props=\"placeholder:\'");

                                                                                                                    Write(Html.TranslateWithPathRaw("to", localizationPath));

WriteLiteral("\',required:true\"");

WriteLiteral(" />\r\n                            <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"twoway\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" data-dojo-type=\"dijit/form/CheckBox\"");

WriteLiteral(" /> ");

                                                                                                              Write(Html.TranslateWithPath("twoway", localizationPath));

WriteLiteral("\r\n                            <button");

WriteLiteral(" data-dojo-type=\"dijit/form/Button\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"epi-primary\"");

WriteLiteral(">");

                                                                                                    Write(Html.TranslateWithPath("addnew", localizationPath));

WriteLiteral("</button>\r\n                        </p>\r\n");



WriteLiteral("                        <h2>");

                       Write(Html.TranslateWithPath("existingsynonyms", localizationPath));

WriteLiteral("</h2>\r\n");

WriteLiteral("                        <div");

WriteAttribute("id", Tuple.Create(" id=\"", 3942), Tuple.Create("\"", 3978)
, Tuple.Create(Tuple.Create("", 3947), Tuple.Create<System.Object, System.Int32>(lang.LanguageId
, 3947), false)
, Tuple.Create(Tuple.Create("", 3965), Tuple.Create("-synonymsGrid", 3965), true)
);

WriteLiteral("></div>\r\n");

                    }

WriteLiteral("                </div>\r\n            </div>\r\n");

        }

WriteLiteral("    </div>\r\n</div>\r\n\r\n<script>\r\n    require(\r\n        [\"dojo/_base/declare\", \"dgr" +
"id/Grid\", \"dijit/form/Button\", \"dijit/form/CheckBox\", \"dojo/domReady!\"],\r\n      " +
"  function (declare, Grid, Button, CheckBox) {\r\n");

            
             foreach (LanguageSynonyms lang in Model.SynonymsByLanguage)
            {

WriteLiteral("                ");

WriteLiteral("\r\n                new Grid({\r\n                        \"class\": \"epi-grid-height--" +
"300 epi-grid--with-border\",\r\n                        columns: {\r\n               " +
"             from: \"");

                              Write(Html.TranslateWithPath("from", localizationPath));

WriteLiteral("\",\r\n                            to: \"");

                            Write(Html.TranslateWithPath("to", localizationPath));

WriteLiteral("\",\r\n                            twoway: {\r\n                                label:" +
" \"");

                                   Write(Html.TranslateWithPath("twoway", localizationPath));

WriteLiteral(@""",
                                renderCell: function (object, value, node) {
                                    new CheckBox({
                                        name: ""twoway"",
                                        checked: object.twoway,
                                        disabled: true
                                    })
                                    .placeAt(node)
                                    .startup();
                                }
                            },
                            actions: {
                                label: """",
                                renderCell: function (object, value, node) {
                                    new Button({
                                            label: """);

                                               Write(Html.TranslateWithPath("delete", localizationPath));

WriteLiteral("\",\r\n                                            iconClass: \"dijitIcon epi-iconTra" +
"sh\",\r\n                                            onClick: function() {\r\n       " +
"                                         if (confirm(\"");

                                                        Write(Html.TranslateWithPath("confirmDelete", localizationPath));

WriteLiteral("\")) {\r\n                                                    window.location = \"");

                                                                  Write(Url.Action("Delete", "ElasticSynonyms"));

WriteLiteral("?index=");

                                                                                                                  Write(ViewBag.SelectedIndex);

WriteLiteral("&languageId=\" + object.lang + \"&analyzer=");

                                                                                                                                                                                   Write(lang.Analyzer);

WriteLiteral(@"&from="" + object.from + ""&to="" + object.to + ""&twoway="" + object.twoway;
                                                }
                                            }
                                        })
                                        .placeAt(node)
                                        .startup();
                                }
                            }
                        }
                    }, """);

                    Write(lang.LanguageId);

WriteLiteral("-synonymsGrid\")\r\n                    .renderArray([\r\n");

                        
                         foreach (var synonym in lang.Synonyms)
                        {

WriteLiteral("                            ");

WriteLiteral("\r\n                                {\r\n                                    from: \"");

                                      Write(Html.Raw(synonym.From));

WriteLiteral("\",\r\n                                    to: \"");

                                    Write(Html.Raw(synonym.To));

WriteLiteral("\",\r\n                                    twoway: ");

                                       Write(synonym.TwoWay.ToString().ToLower());

WriteLiteral(",\r\n                                    lang: \"");

                                      Write(lang.LanguageId);

WriteLiteral("\",\r\n                                    actions: \"\"\r\n                            " +
"    }\r\n                            ");

WriteLiteral("\r\n");

                            
                        Write(synonym != lang.Synonyms.Last() ? "," : null);

                                                                           
                        }

WriteLiteral("                    ]);\r\n                ");

WriteLiteral("\r\n");

            }

WriteLiteral("        }\r\n    );\r\n</script>");

        }
    }
}
#pragma warning restore 1591
